- style:
  class: 2024
  url: /art/disproportionately-affected-study
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--pqAvgiJQ--/c_scale,w_600,q_jpegmini/ashleyjan/2025/11._Disproportionately_affected_study
  title: "Disproportionately Affected Study"
  order: -110
- style: tall
  class: 2024
  url: /art/resolve-study
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--Qryz8oY1--/c_scale,w_600,q_jpegmini/ashleyjan/2025/10._Resolve_study
  title: "Resolve Study"
  order: -105
- style: tall
  class: 2024
  url: /art/resource-seekers-study
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--B41PuAIN--/c_scale,w_600,q_jpegmini/ashleyjan/2025/9._Resource_seekers_study
  title: "Resource Seekers Study"
  order: -100
- style:
  class: 2024
  url: /art/owen
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--NeKqj5ST--/c_scale,w_600,q_jpegmini/ashleyjan/2025/8._Owen
  title: "Owen"
  order: -95
- style:
  class: 2024
  url: /art/kelli
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--l5EW7zu8--/c_scale,w_600,q_jpegmini/ashleyjan/2025/7._Kelli
  title: "Kelli"
  order: -90
- style:
  class: 2024
  url: /art/kelli-kendra-us
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--U9tdIg4h--/c_scale,w_600,q_jpegmini/ashleyjan/2025/6._Kelli_and_Kendra_in_United_States
  title: "Kelli and Kendra in the United States"
  order: -85
- style:
  class: 2024
  url: /art/postartum-seesaw
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--6ZxsOouy--/c_scale,w_600,q_jpegmini/ashleyjan/2025/5._Postpartum_seesaw
  title: "Postpartum seesaw"
  order: -80
- style:
  class: 2024
  url: /art/backyard-respite
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--dq43KBQD--/c_scale,w_600,q_jpegmini/ashleyjan/2025/4._Backyard_respite__United_States
  title: "Backyard Respite (United States)"
  order: -75
- style: tall
  class: 2024
  url: /art/residual-effects
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--kSYXZ7NC--/c_scale,w_600,q_jpegmini/ashleyjan/2025/3._Residual_effects
  title: "Residual Effects"
  order: -70
- style:
  class: 2024
  url: /art/disparity-seesaw
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--m1YTvR7M--/c_scale,w_600,q_jpegmini/ashleyjan/2025/2._Disparity_seesaw_in_U.S
  title: "Disparity Seesaw in U.S."
  order: -65
- style: tall
  class: 2024
  url: /art/equanimity
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--Xgsro7CJ--/c_scale,w_600,q_jpegmini/ashleyjan/2025/1._Equanimity
  title: "Equanimity"
  order: -60
- style:
  class: 2024
  url: /
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--ASjeJJlz--/c_scale,w_800/ashleyjan/2024/Bodily_autonomy
  title: "Bodily Autonomy"
  order: -55
- style:
  class: 2024
  url: /art/support-time-emotion
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--RQ6OUeK1--/c_scale,w_800/ashleyjan/2024/Support_Time_Emotion
  title: "Support, Time, Emotion"
  order: -50
- style: tall
  class: 2024
  url: /art/crystaldylanstudy-3
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--FLSP58li--/c_scale,w_800/ashleyjan/2024/Crystal_and_Dylan_study_3
  title: "Crystal and Dylan Study #3"
  order: -45
- style:
  class: 2024
  url: /art/in-memory-of-baby-roland
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--XWH02YuL--/c_scale,w_800/ashleyjan/2024/In_memory_of_Baby_Roland
  title: "In memory of Baby Roland"
  order: -40
- style:
  class: 2024
  url: /art/chemicalpregnancy
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--kWJogVxo--/c_scale,w_800/ashleyjan/2024/Chemical_Pregnancy
  title: "Chemical Pregnancy"
  order: -35
- style: wide
  class: 2024
  url: /art/kellikendradaughters
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--OGbg-KRv--/c_scale,w_800/ashleyjan/2024/Kelli_Kendra_and_their_daughters
  title: "Kelli, Kendra, and their Daughters"
  order: -30
- style:
  class: 2024
  url: /art/jetaunolivia
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--ShFHVyOo--/c_scale,w_800/ashleyjan/2024/Jetaun_and_Olivia
  title: "Jetaun and Olivia"
  order: -25
- style: tall
  class: 2024
  url: /art/bpstillstudy
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--RRuOJYeW--/c_scale,w_800/ashleyjan/2024/BP_still_life_study
  title: "BP Still Life Study"
  order: -20
- style:
  class: 2024
  url: /art/kylequinnstudy
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--jJlYbW4r--/c_scale,w_800/ashleyjan/2024/Kyle_and_Quinn_study
  title: "Kyle and Quinn study"
  order: -15
- style:
  class: 2024
  url: /art/fiercelovestudy
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--oLxLVGyR--/c_scale,w_800/ashleyjan/2024/Fierce_Love_study
  title: "Fierce Love Study"
  order: -10
- style:
  class: 2024
  url: /art/preeclampsia
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--c6y8sE1s--/c_scale,w_800/ashleyjan/2024/Preeclampsia_affects_1_in_25_pregnancies_in_the_US
  title: "Preeclampsia affects 1 in 25 pregnancies in the US"
  order: -5
- style:
  class: 2023
  url: /art/relatively-smooth-really-listened
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--nxlDKe3F--/c_scale,w_800/ashleyjan/2023/relatively-smooth-really-listened
  title: "Relatively smooth, really listened"
  order: 0
- style:
  class: 2023
  url: /art/exhaling-to-remember
  img_url: //res.cloudinary.com/brightplum/image/upload/v1698271753/ashleyjan/2023/exhaling-to-remember.jpg
  title: "Exhaling to remember"
  order: 5
- style: tall
  class: 2022
  url: /art/32-weeks-4-days-study
  img_url: //res.cloudinary.com/brightplum/image/upload/v1698271753/ashleyjan/2023/32-weeks-4-days-study.jpg
  title: "32 weeks and 4 days study"
  order: 10
- style:
  class: 2023
  url: /art/2021-babies-born-too-early
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--70mbdUkT--/c_scale,w_800/ashleyjan/2023/2021-babies-born-too-early
  title: "In 2021, 1 in 10 babies was born too early in the U.S."
  order: 15
- style:
  class: 2023
  url: /art/kelli-kendra-study
  img_url: https://res.cloudinary.com/brightplum/image/upload/s--vG8o6wF3--/c_scale,w_800/ashleyjan/2023/kelly-and-kendra
  title: "Kelli and Kendra Study"
  order: 20